### ISSUE TITLE
In a 5 man end early if all eligible have rolled

### ISSUE THREAD

**Issue by davidholland** [albertbori/LootRaffle#11]
In the case of a ring or necklace for example, all are eligible.  Lootraffle knows there are 5 people in party and once it receives 5 rolls the raffle will end.  Given a party with 2 leather wearers and 3 plate wearers.... if a leather item is raffled it will go to the full extent of the timer.  Instead have it roll "pass" for the 3 plate wearers so that when the leather wearers do their rolls it will end immediately.

**Comment by albertbori** [comment]
This is actually a bug. Currently, all the people with the loot raffle addon auto-roll (silently) "pass" on ineligible items, leaving those with the roll window open to respond need/greed/DE/pass(close button). Something is preventing the addon from correctly calculating that everyone has rolled to end the raffle early. Intermittent, as it does work from time to time.

**Comment by albertbori** [comment]
Resolved in #18
