### ISSUE TITLE
Lua Error when getting items

### ISSUE THREAD

**Issue by rverghes** [albertbori/LootRaffle#20]
This error has been popping up a lot lately, usually when I loot something that's not a regular item:

Message: Interface\AddOns\LootRaffle\ItemFunctions.lua:5: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: Thu Dec 10 17:28:37 2020
Count: 36
Stack: Interface\AddOns\LootRaffle\ItemFunctions.lua:5: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfo'
[string "@Interface\AddOns\LootRaffle\ItemFunctions.lua"]:5: in function `LootRaffle_GetTradableItemBagPosition'
[string "@Interface\AddOns\LootRaffle\Raffler.lua"]:18: in function `LootRaffle_ProcessLootedItem'
[string "@Interface\AddOns\LootRaffle\Raffler.lua"]:32: in function <Interface\AddOns\LootRaffle\Raffler.lua:32>

Locals: (*temporary) = nil

**Comment by albertbori** [comment]
Seems to be pretty consistent when looting conjured items. (Both mage food & cauldron flasks)
![Screenshot 2020-12-10 221248](https://user-images.githubusercontent.com/1742709/101857242-106fcd00-3b35-11eb-962f-d567bb7dc15d.png)

**Comment by albertbori** [comment]
Fixed in 1.2.3 (6fc443d6d6e58a7fb4892d54b789cd0a1d72c3cc)
