### ISSUE TITLE
Add an ignore list for items not commonly raffled

### ISSUE THREAD

**Issue by davidholland** [albertbori/LootRaffle#6]
Items like defiled augment runes would be nice to ignore.  It would be useful if the addon had a list of these it defaulted with, and the player could manage them to remove/add additional.

**Comment by albertbori** [comment]
Possble v1:
By default, augment runes and shards will be ignored.
/raffle ignore [item link]
/raffle unignore [item link]

Possible v2:
A config GUI with a list of ignored items. [x] button for remove, with an extra button to add.

**Comment by albertbori** [comment]
Resolved in 1.1
